services:
  linuxplayer:
    build: .
    container_name: lucos_media_linuxplayer
    image: lucas42/lucos_media_linuxplayer:${VERSION:-latest}
    environment:
      - MEDIA_MANAGER_URL=https://ceol.l42.eu/
      - KEY_LUCOS_MEDIA_MANAGER
      - KEY_LUCOS_PRIVATE
      - HOSTDOMAIN
      - ENVIRONMENT
    devices:
      - /dev/snd
    restart: always
    healthcheck:
      test: ["CMD", "pgrep", "-f", "npm"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    network_mode: host
