version: '3'
services:
  linuxplayer:
    build: .
    container_name: lucos_media_linuxplayer
    image: lucas42/lucos_media_linuxplayer
    environment:
      - MEDIA_MANAGER_URL=https://ceol.l42.eu/
      - KEY_LUCOS_MEDIA_MANAGER
      - HOSTDOMAIN
    devices:
      - /dev/snd
    restart: always
    network_mode: host
