services:
  linuxplayer:
    build: .
    container_name: lucos_media_linuxplayer
    image: lucas42/lucos_media_linuxplayer
    environment:
      - MEDIA_MANAGER
      - HOSTDOMAIN
    devices:
      - /dev/snd
    restart: always
    network_mode: host
