version: 2.1
orbs:
  lucos: lucos/deploy@0
workflows:
  version: 2
  build-deploy:
    jobs:
      - lucos/build-arm:
          context: docker
      - lucos/deploy-xwing:
          context: docker
          environment:
            CLIENT_UUID: 02db18a0-b29d-4eb1-be6d-e7242de6496e
            CLIENT_NAME: Living Room
          requires:
            - lucos/build-arm
          filters:
            branches:
              only:
                - main
      - lucos/deploy-teltak:
          context: docker
          environment:
            CLIENT_UUID: bc828821-649a-46bd-9624-7ef668022549
            CLIENT_NAME: Bedroom
          requires:
            - lucos/build-arm
          filters:
            branches:
              only:
                - main